/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Patient
         * @description إسناد مريض إلى أخصائي.
         *
         *     الإسناد المنتهي يُعاد تفعيله بدل إنشاء صف ثانٍ: المفتاح الأساسي مركّب
         *     من الطرفين، وصفّ ثانٍ مستحيل أصلًا — لكن الأهم أن عودة مريض إلى
         *     أخصائيه السابق حدث شائع، ومعالجتها كخطأ تجعل الشاشة تكذب.
         */
        post: operations["assign_patient_api_v1_admin_assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/assignments/{specialist_id}/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unassign Patient
         * @description إنهاء الإسناد.
         *
         *     الصف يبقى بـ ``is_active=false`` وتاريخ انتهاء: من كان يتابع هذا
         *     المريض ومتى سؤال سريري يُسأل لاحقًا، وحذف الصف يمحو إجابته.
         */
        delete: operations["unassign_patient_api_v1_admin_assignments__specialist_id___patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Stats */
        get: operations["platform_stats_api_v1_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create Staff User */
        post: operations["create_staff_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description تعديل اسم مستخدم أو دوره أو حالته.
         *
         *     حارسان لا يمكن تجاوزهما:
         *
         *     1. **المدير لا يعطّل نفسه ولا يخفّض دوره.** آخر مدير يفعل ذلك يُغلق
         *        اللوحة على الجميع، ولا يوجد مسار عام لاستعادتها.
         *     2. **الأخصائي ذو المرضى لا يُخفَّض دوره.** قاعدة البيانات ترفضه أصلًا
         *        (مفتاح أجنبي مركّب على ``users(id, role)``)، لكنها ترفضه بخطأ سلامة
         *        غامض؛ هنا يتحول إلى رسالة تقول ما يجب فعله: انقل مرضاه أولًا.
         *
         *     التعطيل ليس ضمن الحارس الثاني عمدًا: تعطيل حساب مخترَق فعل عاجل، وعدد
         *     مرضاه ظاهر في نفس الشاشة فالقرار مبنيّ على معلومة لا على مفاجأة.
         */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/injury-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Injury Types
         * @description أنواع الإصابات المفعّلة، مرتّبة بالمنطقة ثم الاسم.
         */
        get: operations["list_injury_types_api_v1_catalog_injury_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/injuries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Injuries */
        get: operations["list_my_injuries_api_v1_me_injuries_get"];
        put?: never;
        /** Record My Injury */
        post: operations["record_my_injury_api_v1_me_injuries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/injuries/{injury_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Injury Attachments */
        get: operations["list_my_injury_attachments_api_v1_me_injuries__injury_id__attachments_get"];
        put?: never;
        /**
         * Upload My Injury Attachment
         * @description رفع مرفق طبي على إصابة يملكها المستخدم.
         *
         *     القراءة تتم بحد أقصى مقروء من الإعدادات: ``await file.read()`` بلا حد
         *     يحمّل ملفًا بأي حجم إلى الذاكرة قبل أي فحص.
         */
        post: operations["upload_my_injury_attachment_api_v1_me_injuries__injury_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/injuries/{injury_id}/attachments/{attachment_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download My Injury Attachment
         * @description تنزيل محتوى المرفق.
         *
         *     ``Content-Disposition: attachment`` مقصود: عرض ملف رفعه مستخدم داخل
         *     نطاق التطبيق يجعل أي ثغرة في كشف النوع ثغرة XSS مخزَّنة.
         */
        get: operations["download_my_injury_attachment_api_v1_me_injuries__injury_id__attachments__attachment_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Daily Logs */
        get: operations["list_my_daily_logs_api_v1_me_logs_get"];
        put?: never;
        /** Record My Daily Log */
        post: operations["record_my_daily_log_api_v1_me_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Plans
         * @description الخطط المرئية للمريض فقط.
         *
         *     الفلترة على مستوى الاستعلام لا بعد جلب الصفوف: خطة غير معتمدة لا
         *     تُحمَّل أصلًا، فلا يمكن لخطأ في التسلسل أن يسرّبها.
         */
        get: operations["list_my_plans_api_v1_me_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read My Profile */
        get: operations["read_my_profile_api_v1_me_profile_get"];
        /** Upsert My Profile */
        put: operations["upsert_my_profile_api_v1_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Medical Disclaimer
         * @description الموافقة على التنبيه الطبي — شرط قانوني قبل توليد أي خطة.
         */
        post: operations["accept_medical_disclaimer_api_v1_me_profile_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Readings */
        get: operations["list_my_readings_api_v1_me_readings_get"];
        put?: never;
        /** Record My Reading */
        post: operations["record_my_reading_api_v1_me_readings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description يولّد خطة **مسودة**.
         *
         *     المريض يولّد لنفسه، والأخصائي يولّد لمرضاه. الناتج في الحالتين مسودة
         *     لا يراها المريض قبل الاعتماد.
         */
        post: operations["generate_plan_api_v1_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Plan */
        get: operations["read_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Plan
         * @description التفعيل — الخطوة الوحيدة التي تجعل الخطة مرئية للمريض.
         */
        post: operations["activate_plan_api_v1_plans__plan_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description اعتماد الخطة — حكر على الأخصائي والمدير.
         */
        post: operations["approve_plan_api_v1_plans__plan_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Plan History */
        get: operations["read_plan_history_api_v1_plans__plan_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Changes */
        post: operations["request_changes_api_v1_plans__plan_id__request_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit For Review */
        post: operations["submit_for_review_api_v1_plans__plan_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Patients
         * @description قائمة المرضى مع مؤشرات الحالة (الخطوة 8.1).
         */
        get: operations["list_my_patients_api_v1_specialist_patients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Patient Audit
         * @description سجل التدقيق الخاص بمريض (الخطوة 8.5).
         *
         *     القيد يخص المريض إن كان **فاعله** (سجّل إصابة، وافق على التنبيه)، أو
         *     **هدفه** (اطّلع أخصائي على سجله)، أو كان على **خطة من خططه** (اعتماد،
         *     طلب تعديل، تفعيل). الحالة الثالثة هي أهمّ ما يريده الأخصائي وأكثر ما
         *     يسهل نسيانه: فاعلها أخصائي وهدفها خطة، فلا يظهر فيها معرّف المريض
         *     إطلاقًا.
         */
        get: operations["read_patient_audit_api_v1_specialist_patients__patient_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/injuries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Patient Injuries */
        get: operations["read_patient_injuries_api_v1_specialist_patients__patient_id__injuries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Patient Logs
         * @description التسجيل اليومي — مصدر قراءة الالتزام والألم على المدى.
         */
        get: operations["read_patient_logs_api_v1_specialist_patients__patient_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Patient Notes */
        get: operations["read_patient_notes_api_v1_specialist_patients__patient_id__notes_get"];
        put?: never;
        /** Add Patient Note */
        post: operations["add_patient_note_api_v1_specialist_patients__patient_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Patient Plans
         * @description كل خطط المريض — بما فيها المسودات، فهي مادة المراجعة.
         */
        get: operations["read_patient_plans_api_v1_specialist_patients__patient_id__plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Patient Profile */
        get: operations["read_patient_profile_api_v1_specialist_patients__patient_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/patients/{patient_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Patient Readings */
        get: operations["read_patient_readings_api_v1_specialist_patients__patient_id__readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Review Queue
         * @description الخطط المنتظرة مراجعة هذا الأخصائي — شاشة عمله اليومية.
         */
        get: operations["read_review_queue_api_v1_specialist_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityLevel
         * @enum {string}
         */
        ActivityLevel: "sedentary" | "light" | "moderate" | "active" | "very_active";
        /**
         * AdminUserRow
         * @description سطر واحد في قائمة المستخدمين.
         *
         *     الأعداد المرفقة تجيب السؤال الذي يسبق كل قرار في هذه الشاشة: تعطيل
         *     أخصائي عنده مرضى مسنَدون ليس نفس تعطيل أخصائي بلا مرضى، وترقية مريض
         *     له سجل سريري ليست نفس ترقية حساب فارغ.
         */
        AdminUserRow: {
            /** Assigned Patients */
            assigned_patients: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
            /** Specialists */
            specialists: components["schemas"]["AssignedSpecialist"][];
        };
        /**
         * Allergen
         * @description مسبّبات الحساسية الشائعة.
         *
         *     نوع محدود لا نص حر: خطأ إملائي في اسم مسبّب حساسية يعني طعامًا خطرًا
         *     يمر من الفلتر بصمت.
         * @enum {string}
         */
        Allergen: "gluten" | "dairy" | "eggs" | "peanuts" | "tree_nuts" | "soy" | "fish" | "shellfish" | "sesame";
        /**
         * AssignedSpecialist
         * @description أخصائي مسنَد إلى مريض — بالمعرّف لا بالاسم وحده.
         *
         *     الاسم كافٍ للعرض وحده، لكن الشاشة تبني عليه أفعالًا (إنهاء الإسناد،
         *     ترشيح من لم يُسنَد بعد)، والاسم قابل للتكرار بين أخصائيين.
         */
        AssignedSpecialist: {
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * AssignmentRequest
         * @description إسناد مريض إلى أخصائي.
         */
        AssignmentRequest: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Specialist Id
             * Format: uuid
             */
            specialist_id: string;
        };
        /**
         * AttachmentRead
         * @description وصف مرفق طبي — بلا ``storage_key``.
         *
         *     مفتاح التخزين تفصيلة داخلية؛ تسريبه للواجهة يحوّل أي خطأ لاحق في
         *     التحقق من الصلاحية إلى وصول مباشر للملف.
         */
        AttachmentRead: {
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            file_type: components["schemas"]["AttachmentType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Injury Id
             * Format: uuid
             */
            injury_id: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * AttachmentType
         * @enum {string}
         */
        AttachmentType: "xray" | "mri" | "ct_scan" | "ultrasound" | "report" | "photo" | "other";
        /**
         * AuditEntryRead
         * @description سطر من سجل التدقيق كما يُعرض للأخصائي (الخطوة 8.5).
         */
        AuditEntryRead: {
            /** Action */
            action: string;
            /** Actor Name */
            actor_name?: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string | null;
            /** Entity Type */
            entity_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * BodyRegion
         * @enum {string}
         */
        BodyRegion: "shoulder" | "elbow" | "wrist" | "neck" | "upper_back" | "lower_back" | "hip" | "knee" | "ankle" | "foot" | "other";
        /**
         * BodySide
         * @enum {string}
         */
        BodySide: "left" | "right" | "bilateral" | "not_applicable";
        /** Body_upload_my_injury_attachment_api_v1_me_injuries__injury_id__attachments_post */
        Body_upload_my_injury_attachment_api_v1_me_injuries__injury_id__attachments_post: {
            /**
             * File
             * @description صورة أشعة أو تقرير طبي
             */
            file: string;
            file_type?: components["schemas"]["AttachmentType"] | null;
        };
        /**
         * CreateStaffRequest
         * @description إنشاء حساب أخصائي أو مدير — متاح للمدير فقط.
         */
        CreateStaffRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "specialist" | "admin";
        };
        /** DailyLogCreate */
        DailyLogCreate: {
            /** Diet Adherence Pct */
            diet_adherence_pct?: number | null;
            /** Exercise Adherence Pct */
            exercise_adherence_pct?: number | null;
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Notes */
            notes?: string | null;
            /** Pain Level */
            pain_level?: number | null;
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** DailyLogRead */
        DailyLogRead: {
            /** Diet Adherence Pct */
            diet_adherence_pct: number | null;
            /** Exercise Adherence Pct */
            exercise_adherence_pct: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Notes */
            notes: string | null;
            /** Pain Level */
            pain_level: number | null;
            /** Weight Kg */
            weight_kg: string | null;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /**
             * Postgres
             * @enum {string}
             */
            postgres: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
        };
        /**
         * Gender
         * @description يُستخدم في معادلة Mifflin-St Jeor التي تفرّق بين الجنسين.
         * @enum {string}
         */
        Gender: "male" | "female";
        /**
         * Goal
         * @enum {string}
         */
        Goal: "weight_loss" | "muscle_gain" | "maintenance" | "rehabilitation";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InjuryCreate */
        InjuryCreate: {
            /**
             * Had Surgery
             * @default false
             */
            had_surgery: boolean;
            /**
             * Injury Date
             * Format: date
             */
            injury_date: string;
            /**
             * Injury Type Id
             * Format: uuid
             */
            injury_type_id: string;
            /** Notes */
            notes?: string | null;
            /** Pain Level */
            pain_level: number;
            /** Range Of Motion */
            range_of_motion?: {
                [key: string]: unknown;
            };
            /** @default not_applicable */
            side: components["schemas"]["BodySide"];
            /** @default acute */
            status: components["schemas"]["InjuryStatus"];
            /** Surgery Date */
            surgery_date?: string | null;
        };
        /** InjuryRead */
        InjuryRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Phase */
            current_phase: number;
            /** Had Surgery */
            had_surgery: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Injury Date
             * Format: date
             */
            injury_date: string;
            /**
             * Injury Type Id
             * Format: uuid
             */
            injury_type_id: string;
            /** Notes */
            notes: string | null;
            /** Pain Level */
            pain_level: number;
            side: components["schemas"]["BodySide"];
            status: components["schemas"]["InjuryStatus"];
            /** Surgery Date */
            surgery_date: string | null;
        };
        /**
         * InjuryStatus
         * @description مرحلة الإصابة — تحدد ما يُسمح به من تمارين.
         *
         *     ``ACUTE`` تمنع تمامًا أي تمرين مقاومة على المنطقة المصابة (ADR-007).
         * @enum {string}
         */
        InjuryStatus: "acute" | "subacute" | "chronic" | "recovered";
        /**
         * InjuryTypeRead
         * @description نوع إصابة كما يظهر في قائمة اختيار فورم التقييم.
         *
         *     ``is_clinically_reviewed`` جزء من الرد لا تفصيلة داخلية: الواجهة
         *     مُلزَمة بتمييز المحتوى غير المراجَع أمام المستخدم (ADR-003).
         */
        InjuryTypeRead: {
            body_region: components["schemas"]["BodyRegion"];
            /** Description Ar */
            description_ar: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Clinically Reviewed */
            is_clinically_reviewed: boolean;
            /** Name Ar */
            name_ar: string;
            /** Name En */
            name_en: string | null;
            /** Slug */
            slug: string;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MealItemRead */
        MealItemRead: {
            /** Calories */
            calories: string;
            /** Carbs G */
            carbs_g: string;
            /** Fat G */
            fat_g: string;
            /**
             * Food Id
             * Format: uuid
             */
            food_id: string;
            /** Grams */
            grams: string;
            /** Name Ar */
            name_ar: string;
            /** Protein G */
            protein_g: string;
        };
        /** MealRead */
        MealRead: {
            /** Calories */
            calories: string;
            /** Items */
            items: components["schemas"]["MealItemRead"][];
            /** Protein G */
            protein_g: string;
            slot: components["schemas"]["MealSlot"];
        };
        /**
         * MealSlot
         * @enum {string}
         */
        MealSlot: "breakfast" | "lunch" | "dinner" | "snack";
        /** NutritionPlanRead */
        NutritionPlanRead: {
            /** Carbs G */
            carbs_g: string;
            /** Daily Calories */
            daily_calories: number;
            /** Fat G */
            fat_g: string;
            /** Notes Ar */
            notes_ar: string | null;
            /** Protein G */
            protein_g: string;
        };
        /**
         * PatientFlag
         * @description مؤشر حالة المريض في قائمة الأخصائي.
         *
         *     القائمة المرتّبة أبجديًا عديمة الفائدة لأخصائي عنده ثلاثون مريضًا؛ ما
         *     يحتاجه هو **من يستدعي تدخّلًا اليوم**. لذلك المؤشرات مرتَّبة بالأولوية
         *     ويُختار أعلاها لكل مريض:
         *
         *     ``NEEDS_REVIEW``  خطة تنتظر توقيعه — الوحيد الذي يعطّله شخص آخر
         *     ``ACUTE_INJURY``  إصابة حادة مسجَّلة، وهي تُقدَّم على أي هدف
         *     ``STALLED``       لا تسجيل يومي منذ أسبوع — المتابعة انقطعت
         *     ``NOT_STARTED``   لم يستكمل ملفه أو لم يوافق على التنبيه بعد
         *     ``ON_TRACK``      لا شيء يستدعي تدخّلًا
         * @enum {string}
         */
        PatientFlag: "needs_review" | "acute_injury" | "stalled" | "not_started" | "on_track";
        /**
         * PatientSummary
         * @description سطر واحد في قائمة مرضى الأخصائي.
         *
         *     كل ما يحتاجه القرار "أفتح هذا الملف الآن أم لا" مجمَّع هنا في استعلام
         *     واحد. البديل — جلب القائمة ثم نداء لكل مريض — يعني عشرات النداءات
         *     لعرض شاشة واحدة.
         */
        PatientSummary: {
            /** Active Injuries */
            active_injuries: number;
            /** Consent Accepted */
            consent_accepted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days Since Last Log */
            days_since_last_log: number | null;
            /** Diet Adherence Avg */
            diet_adherence_avg: number | null;
            /** Email */
            email: string;
            flag: components["schemas"]["PatientFlag"];
            /** Full Name */
            full_name: string;
            /** Has Active Plan */
            has_active_plan: boolean;
            /** Has Acute Injury */
            has_acute_injury: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Log Date */
            last_log_date: string | null;
            /** Latest Weight Kg */
            latest_weight_kg: string | null;
            /** Plans Awaiting Review */
            plans_awaiting_review: number;
            /** Profile Complete */
            profile_complete: boolean;
            /** Weight Change Kg */
            weight_change_kg: string | null;
        };
        /**
         * PlanGenerateRequest
         * @description طلب توليد خطة.
         *
         *     لا يحتوي حقل ``status``: الخطة المولَّدة تبدأ ``draft`` دائمًا. السماح
         *     بتحديد الحالة عند الإنشاء يفتح طريقًا لخطة تصل المريض بلا مراجعة.
         */
        PlanGenerateRequest: {
            /** @default nutrition */
            plan_type: components["schemas"]["PlanType"];
        };
        /** PlanRead */
        PlanRead: {
            /** Ai Summary */
            ai_summary?: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Approved By Specialist Id */
            approved_by_specialist_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Meals */
            meals?: components["schemas"]["MealRead"][];
            nutrition?: components["schemas"]["NutritionPlanRead"] | null;
            plan_type: components["schemas"]["PlanType"];
            /** Review Notes */
            review_notes?: string | null;
            /** Rule Engine Version */
            rule_engine_version: string;
            status: components["schemas"]["PlanStatus"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * PlanReviewAction
         * @description سبب القرار — يُخزَّن في سجل الانتقالات ويظهر للمريض عند الرفض.
         */
        PlanReviewAction: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * PlanStatus
         * @description حالات الخطة — آلة حالات مفروضة على مستوى قاعدة البيانات (ADR-006).
         *
         *     الانتقالات المسموحة::
         *
         *         draft ──────────▶ pending_review ──▶ approved ──▶ active ──▶ archived
         *           ▲                     │
         *           └── changes_requested ┘
         *
         *     والأرشفة متاحة من أي حالة.
         * @enum {string}
         */
        PlanStatus: "draft" | "pending_review" | "changes_requested" | "approved" | "active" | "archived";
        /** PlanStatusCount */
        PlanStatusCount: {
            status: components["schemas"]["PlanStatus"];
            /** Total */
            total: number;
        };
        /**
         * PlanSummary
         * @description تمثيل مختصر — يُستخدم في القوائم.
         */
        PlanSummary: {
            /** Approved At */
            approved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            plan_type: components["schemas"]["PlanType"];
            /** Rule Engine Version */
            rule_engine_version: string;
            status: components["schemas"]["PlanStatus"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** PlanTransitionRead */
        PlanTransitionRead: {
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            from_status: components["schemas"]["PlanStatus"] | null;
            /** Reason */
            reason: string | null;
            to_status: components["schemas"]["PlanStatus"];
        };
        /**
         * PlanType
         * @enum {string}
         */
        PlanType: "rehab" | "nutrition" | "training" | "combined";
        /**
         * PlatformStats
         * @description أرقام المنصة.
         *
         *     كلها من استعلامات مجمَّعة: العدّ في بايثون بعد جلب الصفوف يعني تحميل
         *     كل مستخدم وكل خطة في الذاكرة لعرض ستة أرقام.
         *
         *     استهلاك الذكاء الاصطناعي وتكلفته (10.3) ينتظران المرحلة 6 — لا يوجد
         *     مزوّد بعد، ورقم مختلَق في لوحة إدارة أسوأ من رقم غائب.
         */
        PlatformStats: {
            /** Active Injuries */
            active_injuries: number;
            /** Acute Injuries */
            acute_injuries: number;
            /** Catalog Exercises */
            catalog_exercises: number;
            /** Catalog Foods */
            catalog_foods: number;
            /** Catalog Injury Types */
            catalog_injury_types: number;
            /** Catalog Unreviewed */
            catalog_unreviewed: number;
            /** Logs Last 7 Days */
            logs_last_7_days: number;
            /** Patients Without Specialist */
            patients_without_specialist: number;
            /** Plans */
            plans: components["schemas"]["PlanStatusCount"][];
            /** Plans Awaiting Review */
            plans_awaiting_review: number;
            /** Users */
            users: components["schemas"]["RoleCount"][];
        };
        /** ProfileRead */
        ProfileRead: {
            activity_level: components["schemas"]["ActivityLevel"];
            /** Age Years */
            age_years: number;
            /** Allergens */
            allergens?: components["schemas"]["Allergen"][];
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Chronic Diseases */
            chronic_diseases: unknown[];
            /** Consent Accepted At */
            consent_accepted_at: string | null;
            gender: components["schemas"]["Gender"];
            goal: components["schemas"]["Goal"];
            /** Height Cm */
            height_cm: string;
            /** Medical History */
            medical_history: unknown[];
            /** Medications */
            medications: unknown[];
            /** Notes */
            notes: string | null;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * ProfileUpsert
         * @description إنشاء أو تحديث الملف الشخصي.
         *
         *     ``birth_date`` لا ``age``: العمر المخزَّن يتقادم بصمت، وإعادة التحليل
         *     اليومية ستحسب السعرات بعمر قديم دون أن يشتكي أحد.
         */
        ProfileUpsert: {
            /** @default sedentary */
            activity_level: components["schemas"]["ActivityLevel"];
            /** Allergens */
            allergens?: components["schemas"]["Allergen"][];
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Chronic Diseases */
            chronic_diseases?: unknown[];
            gender: components["schemas"]["Gender"];
            goal: components["schemas"]["Goal"];
            /** Height Cm */
            height_cm: number | string;
            /** Medical History */
            medical_history?: unknown[];
            /** Medications */
            medications?: unknown[];
            /** Notes */
            notes?: string | null;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            dependencies: components["schemas"]["DependencyStatus"];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** ReadingCreate */
        ReadingCreate: {
            /** Body Fat Pct */
            body_fat_pct?: number | string | null;
            /** Muscle Mass Kg */
            muscle_mass_kg?: number | string | null;
            /**
             * Reading Date
             * Format: date
             */
            reading_date: string;
            /** Resting Hr */
            resting_hr?: number | null;
            /** @default manual */
            source: components["schemas"]["ReadingSource"];
            /** Weight Kg */
            weight_kg?: number | string | null;
        };
        /** ReadingRead */
        ReadingRead: {
            /** Body Fat Pct */
            body_fat_pct: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Muscle Mass Kg */
            muscle_mass_kg: string | null;
            /**
             * Reading Date
             * Format: date
             */
            reading_date: string;
            /** Resting Hr */
            resting_hr: number | null;
            source: components["schemas"]["ReadingSource"];
            /** Weight Kg */
            weight_kg: string | null;
        };
        /**
         * ReadingSource
         * @enum {string}
         */
        ReadingSource: "manual" | "smartwatch" | "device";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterRequest
         * @description التسجيل العام — يُنشئ حساب مريض دائمًا.
         *
         *     لا يوجد حقل ``role`` عمدًا: وجوده يعني أن أي شخص يستطيع طلب صلاحيات
         *     أعلى، وأن أمان النظام يعتمد على تذكّر تجاهله في كل مسار.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** RoleCount */
        RoleCount: {
            /** Active */
            active: number;
            role: components["schemas"]["UserRole"];
            /** Total */
            total: number;
        };
        /**
         * SpecialistNoteCreate
         * @description ملاحظة على مريض.
         *
         *     الحقول في الجسم لا في الـ query string: ملاحظة سريرية قد تكون فقرة
         *     كاملة، ووضعها في الرابط يعني ظهورها في سجلات الخادم وفي تاريخ
         *     المتصفح — وهي بيانات مريض.
         */
        SpecialistNoteCreate: {
            /**
             * Is Internal
             * @default false
             */
            is_internal: boolean;
            /** Note */
            note: string;
            /** Plan Id */
            plan_id?: string | null;
        };
        /** SpecialistNoteRead */
        SpecialistNoteRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Internal */
            is_internal: boolean;
            /** Note */
            note: string;
            /** Plan Id */
            plan_id: string | null;
            /** Specialist Id */
            specialist_id: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserPublic
         * @description التمثيل الوحيد المسموح بإرجاعه للمستخدم — بدون تجزئة كلمة السر.
         */
        UserPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @description أدوار النظام الثلاثة.
         *
         *     التسجيل العام يُنشئ ``PATIENT`` فقط. حسابات الأخصائيين والمديرين
         *     يُنشئها مدير من لوحة الإدارة — لا يوجد أي مسار عام يرفع الصلاحيات.
         * @enum {string}
         */
        UserRole: "patient" | "specialist" | "admin";
        /**
         * UserUpdateRequest
         * @description تعديل مستخدم من لوحة المدير.
         *
         *     الحقول كلها اختيارية: الشاشة ترسل ما تغيّر فقط، فلا يُعاد إرسال الدور
         *     مع كل تفعيل/تعطيل — وإرسال قيمة لم تتغيّر هو أكثر ما يُنتج تعديلات
         *     عرضية في سجل التدقيق.
         *
         *     كلمة السر ليست هنا عمدًا: تغييرها فعل منفصل له مساره الخاص، ووضعه في
         *     نفس الطلب يجعل تعديل اسم يحمل معه خطر إبطال جلسات المستخدم.
         */
        UserUpdateRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assign_patient_api_v1_admin_assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unassign_patient_api_v1_admin_assignments__specialist_id___patient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialist_id: string;
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_stats_api_v1_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStats"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
                search?: string | null;
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_staff_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStaffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_injury_types_api_v1_catalog_injury_types_get: {
        parameters: {
            query?: {
                body_region?: components["schemas"]["BodyRegion"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjuryTypeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_injuries_api_v1_me_injuries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjuryRead"][];
                };
            };
        };
    };
    record_my_injury_api_v1_me_injuries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjuryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjuryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_injury_attachments_api_v1_me_injuries__injury_id__attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                injury_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_my_injury_attachment_api_v1_me_injuries__injury_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                injury_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_my_injury_attachment_api_v1_me_injuries__injury_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_my_injury_attachment_api_v1_me_injuries__injury_id__attachments__attachment_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                injury_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_daily_logs_api_v1_me_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_my_daily_log_api_v1_me_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_plans_api_v1_me_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
        };
    };
    read_my_profile_api_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
        };
    };
    upsert_my_profile_api_v1_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_medical_disclaimer_api_v1_me_profile_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
        };
    };
    list_my_readings_api_v1_me_readings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_my_reading_api_v1_me_readings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_api_v1_plans_generate_post: {
        parameters: {
            query?: {
                patient_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_plan_api_v1_plans__plan_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_api_v1_plans__plan_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanReviewAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_plan_history_api_v1_plans__plan_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanTransitionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_changes_api_v1_plans__plan_id__request_changes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanReviewAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_for_review_api_v1_plans__plan_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_patients_api_v1_specialist_patients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSummary"][];
                };
            };
        };
    };
    read_patient_audit_api_v1_specialist_patients__patient_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_injuries_api_v1_specialist_patients__patient_id__injuries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjuryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_logs_api_v1_specialist_patients__patient_id__logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_notes_api_v1_specialist_patients__patient_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistNoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_patient_note_api_v1_specialist_patients__patient_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistNoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_plans_api_v1_specialist_patients__patient_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_profile_api_v1_specialist_patients__patient_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_patient_readings_api_v1_specialist_patients__patient_id__readings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_review_queue_api_v1_specialist_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSummary"][];
                };
            };
        };
    };
    read_current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
